name: Run tests

on: [push]

jobs:
  all:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      DOWNLOAD_TOKEN: ${{ secrets.DOWNLOAD_TOKEN }}
      ROCKS_USERNAME: ${{ secrets.ROCKS_USERNAME }}
      ROCKS_PASSWORD: ${{ secrets.ROCKS_PASSWORD }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '2.8'

      - name: CMAKE
        run: cmake .

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
